version: "3.1"
services:

  archive:
    container_name: archive 
    build:
      context: .
      dockerfile: docker/archive.dockerfile 
    working_dir: /app
    command: /usr/local/bin/run.sh 
    #command: tail -f /dev/null
    volumes:
      - ./vols/data:/data
      - ./vols/archive:/archive
      - ./vols/home:/home
      - ./vols/tmp:/tmp
    ports:
      - "2222:22"

  apache: 
    container_name: apache
    build:
      context: .
      dockerfile: docker/apache.dockerfile 
    volumes:
      - ./vols/archive:/archive
    command: "apachectl -DFOREGROUND"
    ports:
      - "80:80"

  solr:
    container_name: solr
    build:
      context: .
      dockerfile: docker/solr.dockerfile
    volumes:
      - solr:/var/solr

volumes:
  solr:

