apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: le-staging
  namespace: archive-wiki
spec:
  acme:
    privateKeySecretRef:
      name: le-staging-account
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
       ingress:
         class: nginx
