apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-solr
  namespace: archive-wiki
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: storage-secret
    shareName: solr
    readOnly: false
  mountOptions:
    - dir_mode=0750
    - file_mode=0750
    - gid=8983
    - mfsymlinks
    - nobrl
    - uid=8983
