apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: apache
  name: apache
  namespace: archive-wiki
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: apache
    spec:
      containers:
      - args:
        - apachectl
        - -DFOREGROUND
        image: awimages.azurecr.io/daearchive_apache:latest
        name: apache
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /archive
          name: archive
      restartPolicy: Always
      volumes:
      - name: archive
        persistentVolumeClaim:
          claimName: pvc-archive
status: {}
