apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: solr
  name: solr
  namespace: ingress-basic
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: solr
    spec:
      containers:
      - image: reg24619.azurecr.io/daearchive_solr:v2
        name: solr
        resources: {}
        volumeMounts:
        - mountPath: /var/solr
          name: solr
      restartPolicy: Always
      volumes:
      - name: solr
        azureFile:
          secretName: storage-secret
          shareName: solr
          readOnly: false
status: {}
