apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-home-disk
  namespace: archive-wiki
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-premium
