---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-data
  namespace: archive-wiki
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: pv-data
