---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-tmp
  namespace: ingress-basic
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: pv-tmp
