---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-data
  namespace: ingress-basic
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: pv-data
