apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: apache
  name: apache
  namespace: archive-wiki
spec:
  ports:
  - name: apache-http
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: apache
status:
  loadBalancer: {}
