apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: archive
  name: archive
  namespace: ingress-basic
spec:
  ports:
  - name: archive-ssh
    port: 2222
    targetPort: 22
  - name: archive-api
    port: 3000
    targetPort: 3000
  - name: archive-wiki
    port: 5000
    targetPort: 5000
  selector:
    io.kompose.service: archive
status:
  loadBalancer: {}
