apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: solr
  name: solr
  namespace: archive-wiki
spec:
  ports:
  - name: solr-http
    port: 8983
    targetPort: 8983
  selector:
    io.kompose.service: solr
status:
  loadBalancer: {}
